### PR TITLE
Weather app project

### PR DESCRIPTION
**Pull request by igorkol91**
In this project, I used the openweathermap.org API to develop a personal page that shows current weather.
Features
- Added a default location base on the user location
- Added a form on top of the page that allows users to search any city in the world
- Added clickable temperature that switches to Fahrenheit or Celsius
- Added icons for the current weather and simple explanation next to it
- Added the name of the city currently showing

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Status: Changes required👈

Hey, @igorkol91 your project is really nice, There is only one issue that prevented this project from being approved.

**To highlight:**

- A user is able to search for any city weather condition.
- The app uses promises.
- The repo looks professional, including the readme file.

## Changes to make

- [x] The app should have a toggle control to determine if the result will be shown in Celsius or Fahrenheit (There are two valid solutions: you can make two different requests for the Celsius data and the Fahrenheit data OR make only one request and use math to convert it to the other unit) (screenshot from Odin). **I did not see any button where a user can change from Fahrenheit/Celsius.**

<hr>

## Cheers and Happy coding!👏👏👏

**Feel free to leave any questions or comments in the PR thread if something is not 100% clear.**

**Comment by igorkol91** [comment]
@elisha2kyakpo1 I'm sorry for bothering you I just need a little bit more clarification. I made a cursor pointer on the h2 showing it's clickable and the Celsius/Fahrenheit. They change on click. I should add a button underneath it to change them?

**Comment by elisha2kyakpo1** [comment]
Hey, it was clickable, but it was not changing the data, maybe you can do a button somewhere within the page.

**Review by taiwo2 — APPROVED** [review]
# STATUS: APPROVED 🎉 
@igorkol91 Great job done for implementing suggested changes. Your project is approved kindly merge and prepare for the next project.

[OPTIONAL]
- [ ] It changes its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))

**Pull request merged**
